version: '3.4'

services:
  srp:
    image: srp:dev
    container_name: SRP
    build:
      args:
        source: obj/Docker/empty/
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SRP"
    volumes:
      - C:\Users\moham\source\repos\Solid\SRP:C:\app
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: ""
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
